[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
nalgebra = "0.33.0"
rand = "0.8.5"
tobj = "4.0.2"

[dev-dependencies]
show-image = "0.14.0"
show-image-macros = "0.12.3"
